---
- name: Add mod_status config
  copy:
    dest: /etc/apache2/conf-available/mod_status.conf
    content: "ExtendedStatus on\n<Location /server-status>\n SetHandler server-status\n Require all granted\n</Location>"
  notify: restart apache

- name: Enable mod_status config
  file:
    state: link
    src: /etc/apache2/conf-available/mod_status.conf
    dest: /etc/apache2/conf-enabled/mod_status.conf
